# Generated by Django 2.0.3 on 2018-09-26 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180926_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='page1',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
