# Generated by Django 2.0.3 on 2018-09-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_page1_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page1',
            name='name',
            field=models.IntegerField(choices=[('AMS', 'Amsterdam'), ('ROT', 'Rotterdam'), ('THE', 'The Hague'), ('UTR', 'Utrecht')], default='AMS', max_length=3),
        ),
    ]
