# Generated by Django 2.0.3 on 2018-09-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180929_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='page1',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='page1',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='page1',
            name='phone',
        ),
        migrations.AddField(
            model_name='page1',
            name='How_was_the_event',
            field=models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('A', 'Average')], default='G', max_length=10),
        ),
        migrations.AddField(
            model_name='page1',
            name='Total_no_of_people_using',
            field=models.CharField(choices=[('V', 'Visa'), ('M', 'MasterCard'), ('P', 'Paypal')], default='V', max_length=10),
        ),
        migrations.AlterField(
            model_name='page1',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
