# Generated by Django 2.0.3 on 2018-10-02 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20181001_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='page1',
            name='question1',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
