# Generated by Django 2.0.3 on 2018-10-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20181002_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page1',
            name='question1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
