# Generated by Django 2.0.3 on 2018-11-03 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0015_auto_20181002_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', max_length=200)),
                ('option1', models.CharField(default='', max_length=50)),
                ('option2', models.CharField(default='', max_length=50)),
                ('option3', models.CharField(default='', max_length=50)),
                ('option4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vcet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('A', 'Average'), ('P', 'Poor')], default='G', max_length=10)),
                ('question1', models.CharField(choices=[('E1', 'Excellent'), ('G1', 'Good'), ('A1', 'Average'), ('P1', 'Poor')], default='G1', max_length=10)),
                ('question2', models.CharField(choices=[('E2', 'Excellent'), ('G2', 'Good'), ('A2', 'Average'), ('P2', 'Poor')], default='G2', max_length=10)),
                ('question3', models.CharField(choices=[('E3', 'Excellent'), ('G3', 'Good'), ('A3', 'Average'), ('P3', 'Poor')], default='G3', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='page1',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
