# Generated by Django 2.0.3 on 2020-04-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20181103_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='page1',
            name='card1',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=10),
        ),
        migrations.AlterField(
            model_name='page1',
            name='question1',
            field=models.CharField(choices=[('MS', 'MS'), ('MT', 'MTech'), ('MB', 'MBA'), ('J', 'Job')], default='J', max_length=10),
        ),
    ]
