# Generated by Django 2.0.3 on 2020-04-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200411_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page1',
            name='card1',
        ),
        migrations.RemoveField(
            model_name='page1',
            name='question1',
        ),
    ]
