# Generated by Django 2.0.3 on 2020-04-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20200411_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='page1',
            name='question1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
